# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_yaml12_wrappers", use_symbols = TRUE, package_name = "yaml12")

#' @usage NULL
#' @useDynLib yaml12, .registration = TRUE
NULL

#' Parse a single YAML 1.2 document into base R structures.
#'
#' Supports the common scalar types plus sequences and mappings with string
#' keys; YAML tags, aliases, and other advanced nodes are rejected.
#' @param text Character vector; elements are concatenated with `"\n"`.
#' @export
parse_yaml <- function(text) invisible(.Call(wrap__parse_yaml, text))


# nolint end
